name: 🚀 Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout Repository
      uses: actions/checkout@v3

    - name: 🧰 Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Change this to match your .NET version

    - name: 📦 Restore Dependencies
      run: dotnet restore

    - name: 🏗️ Build Project
      run: dotnet build --configuration Release --no-restore

    - name: ✅ Run Tests
      run: |
        if ls **/*Tests.csproj 1> /dev/null 2>&1; then
          dotnet test --no-build --verbosity normal
        else
          echo "No test project found — skipping tests."
        fi
